# Generated by Django 6.0.8 on 2026-10-06 05:48

import leadflow.users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_demo_principal"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", leadflow.users.models.RevisionUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="auth_revision",
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
    ]
