# Generated by Django 6.0.8 on 2026-10-01 16:52

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='crm_tag_name_ci_unique'), models.CheckConstraint(condition=models.Q(('code__isnull', True), ('code__in', ['website', 'advertising', 'automation', 'other']), _connector='OR'), name='crm_tag_known_system_code')],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('request', models.TextField(max_length=2000)),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('telegram_bot', 'Telegram-бот')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('closed', 'Закрыт')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='leads', to='crm.tag')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeadContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email'), ('telegram', 'Telegram')], max_length=10)),
                ('value', models.CharField(max_length=254)),
                ('key', models.CharField(max_length=254)),
                ('position', models.PositiveIntegerField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.lead')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('lead', 'type', 'key'), name='crm_contact_unique'), models.UniqueConstraint(fields=('lead', 'position'), name='crm_contact_position_unique'), models.CheckConstraint(condition=models.Q(('type__in', ['phone', 'email', 'telegram'])), name='crm_contact_known_type')],
            },
        ),
        migrations.CreateModel(
            name='SubmissionReceipt',
            fields=[
                ('submission_id', models.UUIDField(primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('manual', 'Вручную'), ('telegram_bot', 'Telegram-бот')], max_length=20)),
                ('owner_id', models.BigIntegerField(null=True)),
                ('payload', models.JSONField()),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='crm.lead')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('channel', 'manual'), ('owner_id__isnull', True)), models.Q(('channel', 'telegram_bot'), ('owner_id__gt', 0), ('owner_id__isnull', False)), _connector='OR'), name='crm_receipt_owner_matches_channel')],
            },
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['manual', 'telegram_bot'])), name='crm_lead_known_source'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['new', 'in_progress', 'closed'])), name='crm_lead_known_status'),
        ),
    ]
