# Generated by Django 6.0.8 on 2026-10-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_system_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadcontact',
            name='key',
            field=models.TextField(),
        ),
    ]
