# Generated by Django 6.0.8 on 2026-10-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_leadcontact_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('source_key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
