# Generated by Django 6.0.8 on 2026-10-05 12:36

from hashlib import sha256
import json

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def populate_initial_p1_state(apps, schema_editor):
    database = schema_editor.connection.alias
    Lead = apps.get_model("crm", "Lead")
    CRMState = apps.get_model("crm", "CRMState")
    SubmissionReceipt = apps.get_model("crm", "SubmissionReceipt")

    sequence = 0
    batch = []
    for lead in (
        Lead.objects.using(database)
        .filter(arrival_sequence__isnull=True)
        .order_by("created_at", "pk")
        .iterator(chunk_size=500)
    ):
        sequence += 1
        lead.arrival_sequence = sequence
        batch.append(lead)
        if len(batch) == 500:
            Lead.objects.using(database).bulk_update(batch, ["arrival_sequence"], batch_size=500)
            batch.clear()
    if batch:
        Lead.objects.using(database).bulk_update(batch, ["arrival_sequence"], batch_size=500)
    CRMState.objects.using(database).get_or_create(
        pk=1, defaults={"last_arrival_sequence": sequence}
    )

    receipts = []
    for receipt in SubmissionReceipt.objects.using(database).filter(payload_hash="").iterator(
        chunk_size=500
    ):
        payload = json.dumps(
            receipt.payload,
            sort_keys=True,
            ensure_ascii=False,
            separators=(",", ":"),
            allow_nan=False,
        )
        receipt.payload_hash = sha256(payload.encode("utf-8")).hexdigest()
        receipts.append(receipt)
        if len(receipts) == 500:
            SubmissionReceipt.objects.using(database).bulk_update(
                receipts, ["payload_hash"], batch_size=500
            )
            receipts.clear()
    if receipts:
        SubmissionReceipt.objects.using(database).bulk_update(
            receipts, ["payload_hash"], batch_size=500
        )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_loginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('last_arrival_sequence', models.PositiveBigIntegerField(default=0)),
                ('demo_seeded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MutationReceipt',
            fields=[
                ('operation_id', models.UUIDField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('update_lead', 'Изменение заявки'), ('change_status', 'Смена статуса'), ('delete_lead', 'Удаление заявки'), ('create_tag', 'Создание тега'), ('delete_tag', 'Удаление тега')], max_length=20)),
                ('target_id', models.CharField(max_length=40)),
                ('request_hash', models.CharField(max_length=64)),
                ('applied_version', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['created_at', 'operation_id'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='arrival_sequence',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='note',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='lead',
            name='version',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submissionreceipt',
            name='deleted_lead_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionreceipt',
            name='payload_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='submissionreceipt',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt', to='crm.lead'),
        ),
        migrations.RunPython(populate_initial_p1_state, migrations.RunPython.noop),
    ]
