import type { ThemeConfig } from 'antd'

export const theme: ThemeConfig = {
  token: {
    colorPrimary: '#b5f568',
    colorPrimaryHover: '#c1f781',
    colorPrimaryActive: '#a4e753',
    colorPrimaryBg: '#f2fde8',
    colorPrimaryBgHover: '#e6f8ce',
    colorPrimaryBorder: '#c9ee9e',
    colorLink: '#0958d9',
    colorLinkHover: '#004ab5',
    colorLinkActive: '#003a8c',
    colorText: '#171a21',
    colorTextHeading: '#171a21',
    colorTextSecondary: '#667085',
    colorTextDescription: '#667085',
    colorTextPlaceholder: '#667085',
    colorBgLayout: '#f4f5f7',
    colorBgContainer: '#ffffff',
    colorBorder: '#e3e7eb',
    colorBorderSecondary: '#e3e7eb',
    controlOutline: '#527a20',
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    fontSize: 16,
    fontSizeHeading1: 44,
    fontSizeHeading2: 32,
    fontSizeHeading3: 24,
    fontWeightStrong: 700,
    borderRadius: 20,
    borderRadiusLG: 20,
    borderRadiusSM: 12,
    controlHeight: 44,
    controlHeightLG: 52,
    controlHeightSM: 32,
  },
  components: {
    Button: {
      colorPrimaryBorder: '#527a20',
      primaryColor: '#171a21',
      primaryShadow: 'none',
      defaultShadow: 'none',
      defaultColor: '#171a21',
      defaultHoverColor: '#171a21',
      defaultHoverBg: '#f4f5f7',
      defaultHoverBorderColor: '#cdd3db',
      defaultActiveColor: '#171a21',
      defaultActiveBg: '#eceff3',
      defaultActiveBorderColor: '#b9c1cd',
      fontWeight: 600,
    },
    Table: {
      headerBg: '#ffffff',
      headerColor: '#667085',
      headerSplitColor: 'transparent',
      rowHoverBg: '#f8fcf2',
      rowSelectedBg: '#f2fde8',
      rowSelectedHoverBg: '#e6f8ce',
      cellFontSize: 16,
      cellFontSizeMD: 16,
      cellFontSizeSM: 16,
      cellPaddingBlock: 20,
      cellPaddingInline: 16,
      cellPaddingBlockMD: 18,
      cellPaddingInlineMD: 20,
    },
    Tag: {
      defaultBg: '#eceff3',
      defaultColor: '#171a21',
      borderRadiusSM: 12,
      fontSizeSM: 14,
    },
  },
}
