import { expect, test } from '@playwright/test'
import { enter, incomingLead, mockAccess, noOverflow, screenshot, waitForListResults } from './crmFixtures'

test('mobile app: navigation preserves the filter, reading position and focus', async ({ page, context }, info) => {
  test.skip(info.project.name !== 'phone')
  const server = await mockAccess(context)
  server.leads = Array.from({ length: 20 }, (_, index) => incomingLead(20 - index))
  server.leads.push(incomingLead(21, [{ id: 2, name: 'Реклама', is_system: true }]))
  await page.goto('/')
  await expect(page.getByRole('navigation', { name: 'Управление CRM' })).toHaveCount(0)
  await enter(page, 'demo')
  await waitForListResults(page)
  const dock = page.getByRole('navigation', { name: 'Управление CRM' })
  await expect(dock).toBeVisible()
  await page.getByRole('combobox', { name: 'Направление', exact: true }).click()
  await page.getByText('Сайт', { exact: true }).last().click()
  const lead = server.leads[10]
  const row = page.locator(`[data-lead-id="${lead.id}"]:visible`)
  await row.scrollIntoViewIfNeeded()
  const top = await row.evaluate(element => element.getBoundingClientRect().top)
  await page.getByRole('button', { name: `Открыть карточку: ${lead.name}`, exact: true }).click()
  await expect(page.getByRole('region', { name: 'Карточка заявки' })).toBeVisible()
  await dock.getByRole('button', { name: 'Заявки', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Сбросить фильтр', exact: true })).toBeVisible()
  await expect(page.getByLabel('Всего заявок: 20', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Открыть карточку: Тест автообновления 21', exact: true })).toHaveCount(0)
  await expect.poll(async () => Math.abs(await row.evaluate(element => element.getBoundingClientRect().top) - top)).toBeLessThan(4)
  await expect(page.getByRole('button', { name: `Открыть карточку: ${lead.name}`, exact: true })).toBeFocused()
  await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight))
  const last = page.locator('[data-lead-id]:visible').last()
  await expect.poll(async () => {
    const card = await last.boundingBox()
    const panel = await dock.boundingBox()
    return !!card && !!panel && card.y + card.height <= panel.y
  }).toBe(true)
  await dock.getByRole('button', { name: 'Добавить заявку', exact: true }).click()
  await expect(page.getByLabel('Имя', { exact: true })).toBeVisible()
  await expect(dock).toHaveCount(0)
  await page.getByLabel('Имя', { exact: true }).fill('Тестовый черновик')
  await page.getByRole('button', { name: 'К списку заявок', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Выйти без сохранения?' })).toBeVisible()
  await page.getByRole('button', { name: 'Остаться', exact: true }).click()
  await expect(page.getByLabel('Имя', { exact: true })).toHaveValue('Тестовый черновик')
  await noOverflow(page)
})

test('mobile app: creation from a detail retains the original list position', async ({ page, context }, info) => {
  test.skip(info.project.name !== 'phone')
  const server = await mockAccess(context)
  server.leads = Array.from({ length: 20 }, (_, index) => incomingLead(20 - index))
  await page.goto('/')
  await enter(page, 'demo')
  await waitForListResults(page)
  const lead = server.leads[10]
  const row = page.locator(`[data-lead-id="${lead.id}"]:visible`)
  await row.scrollIntoViewIfNeeded()
  const top = await row.evaluate(element => element.getBoundingClientRect().top)
  await page.getByRole('button', { name: `Открыть карточку: ${lead.name}`, exact: true }).click()
  await page.getByRole('button', { name: 'Добавить заявку', exact: true }).click()
  await page.getByRole('button', { name: 'К списку заявок', exact: true }).click()
  await expect.poll(async () => Math.abs(await row.evaluate(element => element.getBoundingClientRect().top) - top)).toBeLessThan(4)
  await expect(page.getByRole('button', { name: `Открыть карточку: ${lead.name}`, exact: true })).toBeFocused()
})

test('mobile app: menu closes with Escape, restores focus and logs out', async ({ page, context }, info) => {
  test.skip(info.project.name !== 'phone')
  await mockAccess(context)
  await page.goto('/')
  await enter(page, 'demo')
  await waitForListResults(page)
  const menu = page.getByRole('button', { name: 'Меню', exact: true })
  await menu.focus()
  await page.keyboard.press('Enter')
  const dialog = page.getByRole('dialog', { name: 'Меню CRM', exact: true })
  await expect(dialog).toBeVisible()
  const bot = dialog.getByRole('link', { name: 'Открыть Telegram-бота' })
  if (process.env.CRM_TEST_BOT_URL) await expect(bot).toHaveAttribute('href', process.env.CRM_TEST_BOT_URL)
  else await expect(bot).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
  await expect(menu).toBeFocused()
  await menu.click()
  await page.mouse.click(8, 8)
  await expect(dialog).toBeHidden()
  await expect(menu).toBeFocused()
  await menu.click()
  await dialog.getByRole('button', { name: 'Выйти', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Войти', exact: true })).toBeVisible()
  await expect(dialog).toBeHidden()
  await expect(page.getByRole('navigation', { name: 'Управление CRM' })).toBeHidden()
})

test('mobile app: an open menu hides with expired access and stays closed after login', async ({ page, context }, info) => {
  test.skip(info.project.name !== 'phone')
  const server = await mockAccess(context)
  await page.goto('/')
  await enter(page, 'demo')
  await waitForListResults(page)
  await page.getByRole('button', { name: 'Меню', exact: true }).click()
  const menu = page.getByRole('dialog', { name: 'Меню CRM', exact: true })
  await expect(menu).toBeVisible()
  server.expiry = Date.now() - 1
  server.authenticated = false
  await page.evaluate(() => window.dispatchEvent(new Event('focus')))
  await expect(menu).toBeHidden()
  await expect(page.getByRole('navigation', { name: 'Управление CRM' })).toBeHidden()
  await expect(page.getByRole('dialog', { name: 'Вход в CRM', exact: true })).toBeVisible()
  await enter(page, 'demo')
  await expect(page.getByRole('navigation', { name: 'Управление CRM' })).toBeVisible()
  expect(server.logins).toBe(2)
  await expect(menu).toBeHidden()
})

test('mobile app: incoming leads stay above the dock and return focus to the list', async ({ page, context }, info) => {
  test.skip(info.project.name !== 'phone')
  const server = await mockAccess(context)
  server.leads = Array.from({ length: 20 }, (_, index) => incomingLead(20 - index))
  await page.clock.install()
  await page.goto('/')
  await enter(page, 'demo')
  await waitForListResults(page)
  await page.locator('[data-lead-id]:visible').nth(10).scrollIntoViewIfNeeded()
  server.leads.unshift(incomingLead(21))
  await page.clock.fastForward(5000)
  const arrivals = page.getByRole('button', { name: 'Новые заявки: 1 ↑', exact: true })
  await expect(arrivals).toBeVisible()
  const counter = await arrivals.boundingBox()
  const dock = await page.getByRole('navigation', { name: 'Управление CRM' }).boundingBox()
  expect(counter).not.toBeNull()
  expect(dock).not.toBeNull()
  expect(counter!.y + counter!.height).toBeLessThanOrEqual(dock!.y)
  await arrivals.click()
  await expect(page.getByRole('heading', { name: 'Заявки', exact: true })).toBeFocused()
  await expect(page.getByRole('button', { name: 'Открыть карточку: Тест автообновления 21', exact: true })).toBeVisible()
  await expect(arrivals).toHaveCount(0)
})

test('mobile app: approved layout previews preserve draft and fit short viewports', async ({ page, context }, info) => {
  test.skip(info.project.name !== 'phone')
  const server = await mockAccess(context)
  const lead = { ...incomingLead(1), name: 'Анна · тест', request: 'Нужен сайт для студии. Хочу обсудить сроки и стоимость.',
    contacts: [{ type: 'telegram', value: '@anna_demo' }], tags: [{ id: 1, name: 'Сайт', is_system: true }] }
  server.leads = [lead, { ...incomingLead(2), name: 'Марк · тест', request: 'Запустить рекламу нового проекта' },
    { ...incomingLead(3), name: 'София · тест', request: 'Автоматизировать приём заявок' }]
  await page.goto('/')
  await enter(page, 'demo')
  await waitForListResults(page)
  for (const width of [320, 375, 390, 767, 768, 1200, 1440]) {
    await page.setViewportSize({ width, height: 844 })
    await page.evaluate(() => window.scrollTo({ top: 0 }))
    await expect(page.getByRole('heading', { name: 'Заявки', exact: true })).toBeInViewport()
    const dock = page.getByRole('navigation', { name: 'Управление CRM' })
    await expect(dock).toHaveCount(width < 768 ? 1 : 0)
    await noOverflow(page)
    await screenshot(page, `mobile-app-list-${width}`, false)
    if (width < 768) {
      await page.getByRole('button', { name: 'Меню', exact: true }).click()
      await expect(page.getByRole('dialog', { name: 'Меню CRM', exact: true })).toBeInViewport({ ratio: 1 })
      await screenshot(page, `mobile-app-menu-${width}`, false)
      await page.keyboard.press('Escape')
    }
    await page.getByRole('button', { name: `Открыть карточку: ${lead.name}`, exact: true }).click()
    await expect(page.getByRole('link', { name: '@anna_demo', exact: true })).toBeVisible()
    await noOverflow(page)
    await screenshot(page, `mobile-app-detail-${width}`, false)
    await page.getByRole('button', { name: 'К списку заявок', exact: true }).click()
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Меню', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Меню CRM', exact: true })).toBeInViewport({ ratio: 1 })
  await screenshot(page, 'mobile-app-menu-390', false)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Добавить заявку', exact: true }).click()
  await page.getByLabel('Имя', { exact: true }).fill('Анна · тест')
  await page.getByLabel('Контакт 1', { exact: true }).fill('@anna_demo')
  await page.getByLabel('Запрос', { exact: true }).fill(lead.request)
  for (const width of [320, 375, 390, 767, 768, 1200, 1440]) {
    await page.setViewportSize({ width, height: 844 })
    await expect(page.getByLabel('Имя', { exact: true })).toHaveValue('Анна · тест')
    if (width < 768) {
      const actions = page.locator('.crm-form-actions')
      await expect.poll(async () => Math.abs(await actions.evaluate(element => element.getBoundingClientRect().bottom) - 844)).toBeLessThan(2)
    }
    await noOverflow(page)
    await screenshot(page, `mobile-app-form-${width}`, false)
  }
  await page.setViewportSize({ width: 390, height: 420 })
  await page.getByLabel('Запрос', { exact: true }).focus()
  await page.getByLabel('Запрос', { exact: true }).scrollIntoViewIfNeeded()
  const submit = page.getByRole('button', { name: 'Создать заявку', exact: true })
  await expect(submit).toBeInViewport()
  await noOverflow(page)
  await screenshot(page, 'mobile-app-form-short', false)
})
