# Generated by Django 6.0.8 on 2026-10-01 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('telegram_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('last_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.submissionreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('values', models.JSONField(default=dict)),
                ('step', models.CharField(choices=[('name', 'Имя'), ('contacts', 'Контакты'), ('contact_choice', 'Добавить или продолжить'), ('direction', 'Направление'), ('request', 'Запрос'), ('review', 'Проверка')], default='name', max_length=20)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('editing_field', models.CharField(blank=True, max_length=20)),
                ('contact_index', models.PositiveIntegerField(blank=True, null=True)),
                ('question_id', models.BigIntegerField(blank=True, null=True)),
                ('question_date', models.DateTimeField(blank=True, null=True)),
                ('submission_state', models.CharField(default='collecting', editable=False, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='bot.botuser')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('step__in', ['name', 'contacts', 'contact_choice', 'direction', 'request', 'review'])), name='bot_draft_known_step'), models.CheckConstraint(condition=models.Q(('submission_state', 'collecting')), name='bot_draft_active_state')],
            },
        ),
    ]
