# Generated by Django 6.0.8 on 2026-10-02 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotPollingState',
            fields=[
                ('bot_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('next_offset', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('chat_id', models.BigIntegerField()),
                ('text', models.TextField()),
                ('reply_markup', models.JSONField(default=dict)),
                ('submission_id', models.UUIDField(blank=True, null=True)),
                ('draft_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('bind_question', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('delivered', 'Доставлено'), ('failed', 'Ошибка доставки')], default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField()),
                ('last_error', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField()),
                ('next_ordinal', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='draft',
            name='bot_draft_known_step',
        ),
        migrations.RemoveConstraint(
            model_name='draft',
            name='bot_draft_active_state',
        ),
        migrations.AddField(
            model_name='draft',
            name='edit_mode',
            field=models.CharField(choices=[('', 'Нет'), ('replace', 'Заменить'), ('append', 'Дополнить'), ('contact_choice', 'Вернуться к контактам')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='draft',
            name='pending_action',
            field=models.CharField(blank=True, choices=[('', 'Нет'), ('cancel', 'Отменить'), ('restart', 'Начать заново')], max_length=10),
        ),
        migrations.AddField(
            model_name='draft',
            name='pending_revision',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draft',
            name='return_step',
            field=models.CharField(blank=True, choices=[('name', 'Имя'), ('contacts', 'Контакты'), ('contact_choice', 'Добавить или продолжить'), ('direction', 'Направление'), ('request', 'Запрос'), ('review', 'Проверка'), ('paused', 'Пауза')], max_length=20),
        ),
        migrations.AddField(
            model_name='draft',
            name='submission_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='draft',
            name='submission_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='step',
            field=models.CharField(choices=[('name', 'Имя'), ('contacts', 'Контакты'), ('contact_choice', 'Добавить или продолжить'), ('direction', 'Направление'), ('request', 'Запрос'), ('review', 'Проверка'), ('paused', 'Пауза')], default='name', max_length=20),
        ),
        migrations.AlterField(
            model_name='draft',
            name='submission_state',
            field=models.CharField(default='collecting', max_length=20),
        ),
        migrations.AddField(
            model_name='processedupdate',
            name='polling_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.botpollingstate'),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='processed_update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.processedupdate'),
        ),
        migrations.AddField(
            model_name='draft',
            name='pending_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_drafts', to='bot.processedupdate'),
        ),
        migrations.AddConstraint(
            model_name='draft',
            constraint=models.CheckConstraint(condition=models.Q(('step__in', ['name', 'contacts', 'contact_choice', 'direction', 'request', 'review', 'paused'])), name='bot_draft_known_step'),
        ),
        migrations.AddConstraint(
            model_name='draft',
            constraint=models.CheckConstraint(condition=models.Q(('submission_state__in', ['collecting', 'pending'])), name='bot_draft_submission_state'),
        ),
        migrations.AddIndex(
            model_name='processedupdate',
            index=models.Index(fields=['created_at'], name='bot_processed_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='processedupdate',
            constraint=models.UniqueConstraint(fields=('polling_state', 'update_id'), name='bot_processed_update_unique'),
        ),
        migrations.AddIndex(
            model_name='outboundmessage',
            index=models.Index(fields=['status', 'next_attempt_at', 'id'], name='bot_outbound_pending_idx'),
        ),
        migrations.AddConstraint(
            model_name='outboundmessage',
            constraint=models.UniqueConstraint(fields=('processed_update', 'ordinal'), name='bot_outbound_message_order'),
        ),
    ]
