# Generated by Django 6.0.8 on 2026-10-04 12:17

import django.db.models.deletion
from django.db import migrations, models


def backfill_draft_inputs(apps, schema_editor):
    Draft = apps.get_model("bot", "Draft")
    DraftInput = apps.get_model("bot", "DraftInput")
    database = schema_editor.connection.alias
    for draft in Draft.objects.using(database).all().iterator():
        values = dict(draft.values or {})
        direction = values.pop("direction", None)
        directions = values.get("directions")
        if directions is None:
            directions = [direction] if direction else []
        values["directions"] = list(dict.fromkeys(directions))

        if values.get("name"):
            DraftInput.objects.using(database).create(
                draft_id=draft.pk,
                field="name",
                position=0,
                accepted_text=values["name"],
            )
        for position, contact in enumerate(values.get("contacts", [])):
            DraftInput.objects.using(database).create(
                draft_id=draft.pk,
                field="contact",
                position=position,
                accepted_text=contact,
            )
        if values.get("request"):
            DraftInput.objects.using(database).create(
                draft_id=draft.pk,
                field="request",
                position=0,
                accepted_text=values["request"],
            )

        draft.values = values
        missing = next(
            (
                step
                for step, ready in (
                    ("direction", bool(values["directions"])),
                    ("request", bool(values.get("request"))),
                    ("name", bool(values.get("name"))),
                    ("contacts", bool(values.get("contacts"))),
                )
                if not ready
            ),
            "review",
        )
        if draft.submission_state == "collecting":
            if draft.step == "paused":
                draft.return_step = missing
            elif draft.editing_field:
                draft.step = draft.editing_field
                draft.return_step = "review"
            else:
                draft.step = "review" if missing == "review" else missing
        draft.save(update_fields=["values", "step", "return_step"])


def reverse_draft_inputs(apps, schema_editor):
    Draft = apps.get_model("bot", "Draft")
    database = schema_editor.connection.alias
    for draft in Draft.objects.using(database).all().iterator():
        values = dict(draft.values or {})
        directions = values.pop("directions", [])
        if directions:
            values["direction"] = directions[0]
        draft.values = values
        draft.save(update_fields=["values"])
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botpollingstate_outboundmessage_processedupdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('name', 'Имя'), ('contact', 'Контакт'), ('request', 'Описание')], max_length=12)),
                ('position', models.PositiveIntegerField()),
                ('source_message_id', models.BigIntegerField(blank=True, null=True)),
                ('accepted_text', models.TextField()),
                ('pending_text', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('editing_enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['field', 'position', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='draft',
            name='bot_draft_known_step',
        ),
        migrations.AddField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='draft',
            name='active_control_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='draft',
            name='last_username_offer',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='draft',
            name='needs_correction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='draft',
            name='pending_inputs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='delivered_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='interactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='operation',
            field=models.CharField(choices=[('send', 'Отправить'), ('edit_markup', 'Изменить кнопки')], default='send', max_length=16),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='target_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draft',
            name='return_step',
            field=models.CharField(blank=True, choices=[('direction', 'Направления'), ('request', 'Описание'), ('name', 'Имя'), ('contacts', 'Контакты'), ('contact_choice', 'Добавить или продолжить'), ('review', 'Проверка'), ('paused', 'Пауза')], max_length=20),
        ),
        migrations.AlterField(
            model_name='draft',
            name='step',
            field=models.CharField(choices=[('direction', 'Направления'), ('request', 'Описание'), ('name', 'Имя'), ('contacts', 'Контакты'), ('contact_choice', 'Добавить или продолжить'), ('review', 'Проверка'), ('paused', 'Пауза')], default='direction', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='draft',
            constraint=models.CheckConstraint(condition=models.Q(('step__in', ['contacts', 'contact_choice', 'direction', 'request', 'name', 'review', 'paused'])), name='bot_draft_known_step'),
        ),
        migrations.AddField(
            model_name='draftinput',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='bot.draft'),
        ),
        migrations.AddConstraint(
            model_name='draftinput',
            constraint=models.UniqueConstraint(fields=('draft', 'field', 'position'), name='bot_draft_input_position'),
        ),
        migrations.AddConstraint(
            model_name='draftinput',
            constraint=models.UniqueConstraint(fields=('draft', 'source_message_id'), name='bot_draft_source_message'),
        ),
        migrations.RunPython(backfill_draft_inputs, reverse_draft_inputs),
    ]
