# Generated by Django 6.0.8 on 2026-10-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_rethink_bot_intake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundmessage',
            name='operation',
            field=models.CharField(choices=[('send', 'Отправить'), ('edit_text', 'Изменить текст'), ('edit_markup', 'Изменить кнопки')], default='send', max_length=16),
        ),
    ]
