# Generated by Django 6.0.8 on 2026-10-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_outbound_edit_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='last_submission_message_ids',
            field=models.JSONField(default=list),
        ),
    ]
