# Generated by Django 6.0.8 on 2026-10-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remember_submitted_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='review_ui',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
