# Generated by Django 6.0.8 on 2026-10-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_draft_review_ui'),
    ]

    operations = [
        migrations.AddField(
            model_name='botpollingstate',
            name='outbound_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='intake_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botuser',
            name='intake_notice_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botuser',
            name='intake_window_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
