# Generated by Django 6.0.8 on 2026-10-06 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0007_botpollingstate_outbound_retry_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="botpollingstate",
            name="outbound_next_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="botuser",
            name="capacity_notice_update",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capacity_notices",
                to="bot.processedupdate",
            ),
        ),
        migrations.AddField(
            model_name="botuser",
            name="outbound_last_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="botuser",
            name="outbound_next_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
